title: Default Page
preset: page
status:
    draft: Draft
    listed: Listed
    unlisted: Unlisted
    published: Published
fields:
  author:
    type: tags
  date:
    type: date
  text:
    label: Text
    type: textarea
    size: large
    


